import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import ResponsiveAppBar from "@/components/ResponsiveAppBar";
import { Box, Container } from "@mui/material";
import Image from "next/image";
import tanjiro from "./../../public/tanjiro.png";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Anime Universe",
  description: "Generated by Tanmay & Dharan",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        {/* <Image
          alt="Tanjiro"
          src={tanjiro}
          height={500}
          style={{
            position: "fixed",
            right: 0,
          }}
        /> */}
        <AppRouterCacheProvider options={{ key: "css" }}>
          <ThemeProvider theme={theme}>
            <ResponsiveAppBar />
            <Box
              sx={{
                width: "100%",
                backgroundImage: "linear-gradient(180deg, #CEE5FD, #FFF)",
                backgroundRepeat: "no-repeat",
                minHeight: "100vh",
              }}
            >
              <Container sx={{ paddingBottom: 10 }}>{children}</Container>
            </Box>
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
